package com.algotrade.authservice.service.token;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Optional;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.algotrade.authservice.auth.config.JwtProperties;
import com.algotrade.authservice.model.RefreshToken;
import com.algotrade.authservice.model.User;
import com.algotrade.authservice.repository.RefreshTokenRepository;
import com.algotrade.authservice.service.jwt.JwtService;


@Service
@Transactional
public class RefreshTokenService {

	private final RefreshTokenRepository refreshTokenRepository;
	private final JwtService jwtService;
	private final JwtProperties jwtProperties;

	public RefreshTokenService(RefreshTokenRepository refreshTokenRepository,
			JwtService jwtService,
			JwtProperties jwtProperties) {
		this.refreshTokenRepository = refreshTokenRepository;
		this.jwtService = jwtService;
		this.jwtProperties = jwtProperties;
	}

	/**
	 * Creates a new refresh token for the given user.
	 * The raw token is generated by JwtService, hashed with SHA‑256,
	 * and stored in the database. The raw token is returned only once.
	 *
	 * @param user the authenticated user
	 * @return the raw refresh token string (to be sent to client)
	 */
	public String createRefreshToken(User user) {
		// 1. Generate a random opaque token
		String rawToken = jwtService.generateRefreshToken();

		// 2. Hash the raw token before storing
		String tokenHash = hash(rawToken);

		// 3. Build the entity
		RefreshToken refreshToken = new RefreshToken();
		refreshToken.setTokenHash(tokenHash);
		refreshToken.setUser(user);
		refreshToken.setExpiryDate(Instant.now().plus(
				jwtProperties.getRefreshTokenLifetimeSeconds(), ChronoUnit.SECONDS));
		refreshToken.setRevoked(false);

		refreshTokenRepository.save(refreshToken);

		return rawToken;
	}

	/**
	 * Verifies a raw refresh token (hash it, look it up, check expiry and revocation).
	 *
	 * @param rawToken the raw token from the client
	 * @return the valid RefreshToken entity if found and valid, otherwise empty
	 */
	@Transactional
	public Optional<RefreshToken> verifyRefreshToken(String rawToken) {
		String tokenHash = hash(rawToken);
		Optional<RefreshToken> tokenOpt = refreshTokenRepository.findByTokenHash(tokenHash);

		if (tokenOpt.isEmpty()) {
			return Optional.empty();
		}

		RefreshToken token = tokenOpt.get();

		// Replay detection: if token is already revoked, possible theft → revoke all tokens of user
		if (token.isRevoked()) {
			refreshTokenRepository.revokeAllByUser(token.getUser());
			return Optional.empty();
		}

		if (token.getExpiryDate().isBefore(Instant.now())) {
			return Optional.empty();
		}

		return Optional.of(token);
	}

	/**
	 * Revokes a refresh token (e.g., on logout or rotation).
	 *
	 * @param token the RefreshToken entity to revoke
	 */
	public void revokeRefreshToken(RefreshToken token) {
		token.setRevoked(true);
		refreshTokenRepository.save(token);
	}

	/**
	 * Revokes all refresh tokens for a user (e.g., on password change).
	 */
	@Transactional
	public void revokeAllUserTokens(User user) {
		refreshTokenRepository.revokeAllByUser(user);
	}

	/**
	 * Hashes a string using SHA‑256.
	 */
	private String hash(String raw) {
		try {
			MessageDigest md = MessageDigest.getInstance("SHA-256");
			byte[] hashBytes = md.digest(raw.getBytes(StandardCharsets.UTF_8));
			StringBuilder hexString = new StringBuilder();
			for (byte b : hashBytes) {
				String hex = Integer.toHexString(0xff & b);
				if (hex.length() == 1) hexString.append('0');
				hexString.append(hex);
			}
			return hexString.toString();
		} catch (NoSuchAlgorithmException e) {
			throw new RuntimeException("SHA‑256 not available", e);
		}
	}
}